env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  __PATH_PREFIX__: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - unused-imports
  - prettier
rules:
  no-empty:
    - error
    - allowEmptyCatch: true
  no-var:
    - error
  object-shorthand:
    - error
  curly:
    - error
  eqeqeq:
    - error
  no-alert:
    - error
  no-console:
    - error
  no-shadow-restricted-names:
    - error
  array-bracket-spacing:
    - error
  brace-style:
    - error
  camelcase:
    - error
  comma-spacing:
    - error
  eol-last:
    - error
  key-spacing:
    - error
  no-lonely-if:
    - error
  no-multiple-empty-lines:
    - error
  no-spaced-func:
    - error
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  semi-spacing:
    - error
  semi:
    - error
    - never
  keyword-spacing:
    - error
  space-before-blocks:
    - error
  space-in-parens:
    - error
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
